
const config = {
    BICONOMY_AUTH_TOKEN: process.env.REACT_APP_BICONOMY_AUTH_TOKEN,
    BICONOMY_MUMBAI_DAPP_API_KEY: process.env.REACT_APP_BICONOMY_MUMBAI_DAPP_API_KEY,
    BICONOMY_GOERLI_DAPP_API_KEY: process.env.REACT_APP_BICONOMY_GOERLI_DAPP_API_KEY,
    BICONOMY_MUMBAI_DEPLOY_METHOD_ID: process.env.REACT_APP_BICONOMY_MUMBAI_DEPLOY_METHOD_ID,
    BICONOMY_GOERLI_DEPLOY_METHOD_ID: process.env.REACT_APP_BICONOMY_GOERLI_DEPLOY_METHOD_ID,
};
  
  export default { config };
  